### ISSUE TITLE
prticaa

### ISSUE THREAD

**Issue by 0eeixl** [SistemasTecTlaxiaco/practica-de-relaciones-equipo-julio-cesar-gonzalez-lopez#4]
[patica,,,eri,,ag,gar.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-relaciones-equipo-julio-cesar-gonzalez-lopez/files/12835467/patica.eri.ag.gar.pdf)

**Comment by elisa1223** [comment]
Portada: 22%
Procedimiento: 17%
Figuras, ilustraciones y fotografias 25%
Resultados y conclusiones 20%(no describe resultados)
Calificacion final: 16.8 / 20
Evaluado por el equipo de Elisa Sánchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
